server:
  port: 9090
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.83.100:3306/springbootdemo?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    #type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  #config-location: classpath:/mybatis/mybatis-config.xml #指定主配置文件
  #mapper-locations: classpath:/mybatis/mapper/*.xml # 指定xml映射文件路径
  type-aliases-package: com.atguigu.pojo # 指定mybatis别名包
logging:
  level:
    com.atguigu.dao: debug # 配置日志